### ISSUE TITLE
colors in quotes

### ISSUE THREAD

**Issue by smiller171** [clifford-github/sublime-ansible#16]
anything between quotes should have its own syntax color

**Comment by pchaigno** [comment]
@clifford-github I think he means that everything inside single or double quotes should be highlighted as a string. So, keywords shouldn't be highlighted inside quotes (except maybe for Ansible variables).
For instance, see the line `line='start on filesystem'` in [this code](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fclifford-github%2Fsublime-ansible%2Fmaster%2FAnsible.tmLanguage&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fawailly%2Fcis-ubuntu-ansible%2Fmaster%2Ftasks%2Fsection_08_level1.yml&code=-+name%3A+8.2.5.2+Configure+rsyslog+to+Send+Logs+to+a+Remote+Log+Host+%28Scored%29%0D%0A++++lineinfile%3A%0D%0A+++++++dest%3D%2Fetc%2Frsyslog.conf%0D%0A+++++++line%3D%27start+on+filesystem%27%0D%0A+++++++insertafter%3DEOF%0D%0A+++++++state%3Dpresent).

**Comment by smiller171** [comment]
I've since moved on To Atom, but @pchaigno is on the right track.

**Comment by killua99** [comment]
I'm closing this issue since the package as been rewritten from scratch. Feel free open a new issue when the new package hit mainstream
