### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [clifford-github/sublime-ansible#20]
I would like to use your grammar for Ansible but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by clifford-github** [comment]
Never thought about this before. The MIT License is OK for me.

May I ask what you are using the grammar for?

**Comment by pchaigno** [comment]
I'm thinking about using it to highlight Ansible code on GitHub (see [github/linguist](https://github.com/github/linguist)).

Could you add the license in a file in the repository or in your `README.md`?

**Comment by clifford-github** [comment]
I feel honored and have added the license file LICENSE.md

**Comment by pchaigno** [comment]
Thanks! :sparkles:
