### ISSUE TITLE
First item in list

### ISSUE THREAD

**Issue by BarbzYHOOL** [clifford-github/sublime-ansible#25]
When there is a list, and it doesn't start by "- name:" then it's not highlighted

Example:

```
list:
  - test: 1
```

test will be in white

**Comment by killua99** [comment]
I'm closing this issue since the package as been rewritten from scratch. Feel free open a new issue when the new package hit mainstream

**Comment by BarbzYHOOL** [comment]
how do i update it? @killua99

**Comment by killua99** [comment]
Follow the instructions on Readme to install it from control package @BarbzYHOOL

**Comment by BarbzYHOOL** [comment]
> Follow the instructions on Readme to install it from control package @BarbzYHOOL

if i list in control: install package, it's not there because I already have it installed, do I have to remove it first?
