### ISSUE TITLE
Simpler regex using non-greedy star

### ISSUE THREAD

**Issue by Alexey-T** [clifford-github/sublime-ansible#29]
match: (\{\{ *[^\{\}]+ *\}\})|(\$\{[^\{\}]+\})
  
This can be much simpler. Use star-char with non-greedy modifier ? . Eg a.*?a finds text inside a chars.

**Comment by killua99** [comment]
I'm closing this issue since the package as been rewritten from scratch. Feel free open a new issue when the new package hit mainstream
