### ISSUE TITLE
Coloring in Jinja expressions seems off

### ISSUE THREAD

**Issue by Nothing4You** [clifford-github/sublime-ansible#37]
f83b56aa0a236264daa291c24f586fdcb2bedee4

```yaml
---

- debug:
    msg: "{{ foo }}"

- debug:
    msg: "{{ foo[bar]['baz'] }}"

- debug:
    msg: "{{ lookup('plugin_name', 'arg_value') | selectattr('foo', 'defined') }}"
```

<img width="633" alt="image" src="https://user-images.githubusercontent.com/3694534/205569538-b749ad26-9643-46a5-8fc7-48f6babd5436.png">

I'm not sure what I'd expect this to look like but this seems inconsistent and doesn't look right, especially with keywords (in quotes) being highlighted.

**Comment by Nothing4You** [comment]
The keyword aspect seems to apply everywhere, would it make sense to restrict them to `when`?

```yaml
---

- debug:
    msg: what else could happen
  when:
    - "foo" == "bar"
    - "foo" == "else"
```

<img width="267" alt="image" src="https://user-images.githubusercontent.com/3694534/205571975-d1770dfc-151d-47dd-80e2-79c7a655af1a.png">

**Comment by killua99** [comment]
I turn off the keyword meanwhile I find a better way to catch them when they make sense
