### ISSUE TITLE
Sublime text recommends putting user specific data in Packages/User

### ISSUE THREAD

**Issue by darKoram** [clifford-github/sublime-ansible#7]
The video link https://tutsplus.com/lesson/key-bindings/ has some excellent sublime tutorials.  They (and i think sublime proper) recommend putting user comstimizations in  Packages/User rather than Packages.  Otherwise, if you upgrade sublime, you will lose all personal customizations.

I recommend you modify the README.de to use this best practice.

**Comment by killua99** [comment]
I'm closing this issue since the package as been rewritten from scratch. Feel free open a new issue when the new package hit mainstream
