### ISSUE TITLE
templates jinja

### ISSUE THREAD

**Issue by darKoram** [clifford-github/sublime-ansible#8]
I think i mentioned it in a previous issue as a comment, but putting it here as a proper issue.  It would be nice to default any file without recognized extension to be a .j2 file and use the sublime plugin for jinja2.  If the file in templates is a bash script (or python or whatever), it is probably best to leave it as is.

kesten

**Comment by ashemedai** [comment]
As a workaround, you can always install ApplySyntax and in the user configuration for ApplySyntax have something like the following:

```json
{
    "syntaxes": [
        {
            "syntax": "Jinja2/Syntaxes/Jinja Templates",
            "rules": [
                { "file_path": ".*/templates/.*.j2$" }
            ]
        }
    ]
}
```

Adjust accordingly to whatever you use for layout, although this should fit well for the BCP for directory layouts mentioned in http://docs.ansible.com/playbooks_best_practices.html#directory-layout

**Comment by BarbzYHOOL** [comment]
The above thing does strictly nothing...

**Comment by killua99** [comment]
I'm closing this issue since the package as been rewritten from scratch. Feel free open a new issue when the new package hit mainstream
